import type { Metadata } from 'next';
import { Schoolbell } from 'next/font/google';
import '../styles/globals.css';
import Header from '@/components/header';

const schoolbell = Schoolbell({
  weight: '400',
  // preload: false,
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    template: '%s | 🦖',
    default: '🦖',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={schoolbell.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
